---
apiVersion: v1
kind: Service
metadata:
  name: authoring
  labels:
    app: authoring-datacollector
spec:
  type: NodePort
  ports:
  - name: http
    port: 18635
    targetPort: 18630
    protocol: TCP
  selector:
    app: authoring-datacollector
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: authoring-sdc
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host:
    http:
      paths:
      - path: /
        backend:
          serviceName: authoring
          servicePort: 18635
