apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: authoring-datacollector
  namespace: ns1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app : authoring-datacollector
    spec:
      containers:
      - name : authoring-datacollector
        image: streamsets/datacollector:latest
        ports:
        - containerPort: 18630
        env:
        - name: SDC_CONF_SDC_BASE_HTTP_URL
          value: https://authsdc.onefoursix.com
        - name: SDC_CONF_HTTP_ENABLE_FORWARDED_REQUESTS
          value: true
